### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by pieterdd** [Festify/ken-burns-carousel#3]
I'm getting the following error in my browser:

```
ReferenceError: customElements is not defined ken-burns-carousel.ts:3
<anonymous>
ken-burns-carousel.ts:3
<anonymous>
https://festify.github.io/ken-burns-carousel/ken-burns-carousel.min.js:1:155
<anonymous>
https://festify.github.io/ken-burns-carousel/ken-burns-carousel.min.js:1:2
```

Here's the offending file:
```
import Carousel from './element.js';

customElements.define('ken-burns-carousel', Carousel);

export default Carousel;
```

This happens when I include the package using `import from 'ken-burns-carousel'` syntax, when I load the minified version from the example site and when I load it from UNPKG. Is this a bug or misconfiguration?

**Comment by NeoLegends** [comment]
Hey, could you tell us which browser you're using?

The element (intentionally) expects the browser to have web component support (the missing `window.customElements` object). If you're using a browser that does not feature web components, please load a polyfill (https://github.com/webcomponents/webcomponentsjs) before loading the element. :)

**Comment by pieterdd** [comment]
Currently on Firefox 62. Okay, loading the polyfill will probably do the trick!

**Comment by pieterdd** [comment]
It did, thanks :)
